language: objective-c
osx_image: xcode8.2
xcode_workspace: photowall.xcworkspace
xcode_scheme: photowall

script:
  - xcodebuild -scheme photowall -workspace photowall.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.0' build test

after_success:
  - bash <(curl -s https://codecov.io/bash)